### ISSUE TITLE
Binary Symlink Points to Debug Build

### ISSUE THREAD

**Issue by killercup** [ohjames/mr_t_init#1]
`target/debug/lovely_touching` -> `target/release/lovely_touching`

If there were any install/compile instruction, I'd also tell you to change it to `cargo build --release` ;)

**Comment by insidewhy** [comment]
That symlink is just for my stupid manual testing, I'll add some actual tests soon and delete the symlink. Probably shouldn't have committed it in the first place.

Will add the `cargo build --release` line to the README, Soon I'll compile it in a Centos5 container and provide a binary for people to use directly.

**Comment by insidewhy** [comment]
I've added the centos5 docker build and the build instructions now. Removed that symlink also.

Since I can now provide two binaries that'll cover ~99.9% of linux systems I guess most people will just download the binary directly!

docker/rust are so cool.
