### ISSUE TITLE
Rename?

### ISSUE THREAD

**Issue by matschaffer** [ohjames/mr_t_init#2]
This looks like a handy tool but man do I feel silly every time I have to talk about it with a co-worker.

How about `rinit` (since it's rust) to compliment `sinit`?

**Comment by insidewhy** [comment]
I will do it but only if you change your name from "Mat" to "Matt".

**Comment by insidewhy** [comment]
I won't really do it. Life is too boring enough as it is and people are too conservative.

Sure you could go on using the same old types of names to describe the same old types of things and all our companies will be called giffr or sprkly or crnchy.io and there will be no joy.

Or we could throw around  brave new names with reckless wanton:

"Hey Brad, did you see this new tool called `My Face Burns like Petals` for synergizing my monetizes?"
"Oh Chase wow, I truly appreciate this bold new name."

Life can be fun if you let it be fun! Down with conservative naming and conservative people and conservative politics. HAIL THE REVOLUTION.

**Comment by matschaffer** [comment]
Ha! You, sir, have shown me the light. Thank you.

**Comment by matschaffer** [comment]
lovely_touching it is then :)

On Thursday, July 2, 2015, Mr Friend notifications@github.com wrote:

> I will do it but only if you change your name from "Mat" to "Matt".
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ohjames/lovely_touching/issues/2#issuecomment-117968050
> .

## 

-Mat

about.me/matschaffer
